<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eShop.Web.Module\eShop.Web.CustomerPortal\eShop.Web.CustomerPortal.csproj" />
    <ProjectReference Include="..\..\eShop.Web.Module\eShop.Web.AdminPortal\eShop.Web.AdminPortal.csproj" />
    <ProjectReference Include="..\..\eShop.Web.Module\eShop.Web.Common\eShop.Web.Common.csproj" />
    <ProjectReference Include="..\..\eShop.UseCases\eShop.UseCases.csproj" />
    <ProjectReference Include="..\..\eShop.CoreBusiness\eShop.CoreBusiness.csproj" />
    <ProjectReference Include="..\..\Plugins\eShop.DataStore.HardCode\eShop.DataStore.HardCode.csproj" />
    <ProjectReference Include="..\..\Plugins\eShop.DataStore.SQL.Dapper\eShop.DataStore.SQL.Dapper.csproj" />
  </ItemGroup>

</Project>
